### ISSUE TITLE
add more embedding_model type

### ISSUE THREAD

**Issue by Gierry** [langchain4j/langchain4j-embeddings#2]
Hello author, this is a great engineering project, I have been following your progress, but I am a Chinese user, the biggest challenge I face is Chinese word segmentation, so I hope to add more of word segmentation embedding_model type, thank you very much, just like this: 

    "nghuyong/ernie-3.0-nano-zh",
    "nghuyong/ernie-3.0-base-zh",
    "shibing624/text2vec-base-chinese",
    "GanymedeNil/text2vec-large-chinese",
    "shibing624/text2vec-base-multilingual",
    "shibing624/text2vec-base-chinese-sentence",
    "shibing624/text2vec-base-chinese-paraphrase",
    "moka-ai/m3e-small",
    "moka-ai/m3e-base",

this is from the project:  https://github.com/chatchat-space/langchain-ChatGLM/blob/master/README_en.md

Thank you

**Comment by langchain4j** [comment]
Hi @Gierry thanks for the kind words!

Almost all of the models you listed are very big in size (much more than all-minilm-l6-v2 and e5-small-v2 which are 20-80MB) , so it will be impractical to keep them inside langchain4j jar artefacts.
In the next release (probably today or tomorrow) there will be a possibility to use any custom in-process embedding model.
So you can convert one of those into ONNX format and plug it into langchain4j.

I can offer to add support for m3e-small(quntized) or ernie-3.0-nano-zh, but I need to be sure that they perform well. Did you tests them already (via huggingface inference API or in other way)? Do they perform well for Chinese?

Another alternative is https://huggingface.co/intfloat/multilingual-e5-small (supports Chinese as well) which has a satisfactory score on MTEB leaderboard: https://huggingface.co/spaces/mteb/leaderboard

**Comment by Gierry** [comment]
Hello @langchain4j , thank you very much for such a quick answer. The word segmentation models I listed are very popular in the Chinese industry at present.
      As for the question of had I tested them, you can take a look at the homepage of these word segmentation models. I believe they have been strictly tested. 
      After all, Chinese word segmentation is the most complicated language. In addition, most users do have a demand for large-scale word segmentation services. 
     This is also an urgent need in the industry. Therefore, if it is not convenient to put large word segmentation models in the project, 
     I hope  you  can add a word segmentation tool in the form of an interface, and the user can call the large model word segmentation service deployed by himself (via RPC or HTTP protocol) after implementing your method

   Thank you very much

**Comment by langchain4j** [comment]
@Gierry I have just discovered MTEB for Chinese: https://github.com/FlagOpen/FlagEmbedding/tree/master/C_MTEB
This model looks very promising (for retrieval): https://huggingface.co/BAAI/bge-small-zh
Going to add it to langchain4j soon.

**Comment by Gierry** [comment]
ok ,thank you very much

**Comment by langchain4j** [comment]
@Gierry we've added bge-small-zh in 2 versions: full (`langchain4j-embeddings-bge-small-zh`) and quantized (`langchain4j-embeddings-bge-small-zh-q`) in 0.20.0
